### ISSUE TITLE
Add Cancel button for editing a post

### ISSUE THREAD

**Issue by kellim** [udacityalumni/udacity-alumni-fe#146]
When you are editing a post, it only has submit and preview buttons. It would be nice to have a Cancel button as well.

**Comment by RyanCCollins** [comment]
Hey @kellim what would cancel button do?  Redirect to the dashboard?

**Comment by RyanCCollins** [comment]
I've added a back to dashboard button that'll show when a user is editing a post.

**Comment by kellim** [comment]
Yes, it would redirect to the page you were at before you started editing a post. A back to dashboard button should be good enough, it was just that I wanted a way to get out of creating a post.

**Comment by ghoshabhi** [comment]
@kellim : Was this issue resolved ?

**Comment by kellim** [comment]
Yes, we have a back button now that will return you to the dashboard if you wish to cancel editing a post.

**Comment by kellim** [comment]
Maybe we need another issue for no way to get out of creating a NEW post, as it seems the back button is only for editing existing posts. I will start a new issue.
