### ISSUE TITLE
Component Docs

### ISSUE THREAD

**Issue by JamesIves** [udacityalumni/udacity-alumni-fe#159]
The following **component** docs need to be updated. Creating an issue to keep track.

- components/AppNavigation
- components/AppCalendar
- components/ArticleFeedItem
- components/Avatar
- components/CarouselWidget
- components/CmsEditor
- components/CmsEditorPreview
- components/CmsModal
- components/ConfirmationModal
- components/DashboardTable
- components/DashboardTableButtonMenu
- components/Divider
- components/LinkList
- components/LoginForm
- components/LostPasswordModal
- components/MartinRulz
- components/Member
- components/PasswordResetForm
- components/ResponsiveImage
- components/SessionMenu
- components/SingleArticleContent
- components/TagEditor
- components/UserProfile

**Comment by JamesIves** [comment]
components/Avatar is fixed in #158

**Comment by zhangtreefish** [comment]
Hi @JamesIves ! Is this close to what you had in mind when you once mentioned the component relationships: https://www.npmjs.com/package/react-monocle  ? It would be cool to be able to visualize the app. I couldn't figure out where the 'bundled webpack file' is.
